services:
  - type: web
    name: study-hall-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: STUDY_HALL_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: STUDY_HALL_SECRET_KEY
        generateValue: true
      - key: STUDY_HALL_ADMIN_USER
        sync: false
      - key: STUDY_HALL_ADMIN_PASSWORD
        sync: false
